### ISSUE TITLE
invite pausing/disabling

### ISSUE THREAD

**Issue by Ixrec** [Manechat/izzy-moonbot#106]
It would be nice if Izzy automatically paused invites when she detects a raid or we run `.ass` (not sure which), and re-enabled them when the raid was over or we run `.assoff`.

I don't think we have a use case for a dedicated `.pauseinvites` command, since that's already a single big red button in Discord's UI.

**Comment by Ixrec** [comment]
After several months of Izzy usage and not a single large raid, I think this is the sort of feature that sounds nice in theory but even if we could implement it we'd all forget it exists by the time it mattered and end up clicking Discord's big red button anyway. If it was an easy method call in the Discord.NET API, maybe, but if we have to do it raw then I don't think it's worth it.

**Comment by cloudburstwan** [comment]
Discord.NET is yet to add a method to handle this, so we'll put this on hold until it's required.
