### ISSUE TITLE
consider auto-timeout-ing a user who trips spam/filter after already being silenced

### ISSUE THREAD

**Issue by Ixrec** [Manechat/izzy-moonbot#169]
In #modchat discussion of today's moon spam incident, several suggestions were made, and we believe the optimal solution is:
- Add Banished and Welcome to SpamBypassRoles. Anyone who we manually put in there, it's on us to deal with; Izzy getting involved only confuses things.
- If a silenced user spams, automatically apply slow mode to that channel.

Finding an API for this took a minute, but it appears to be:
```cs
        socketTextChannel.ModifyAsync(cp => cp.SlowModeInterval = 10);
```

Until and unless we do #103, "a silenced user spams" should only be possible in welcome. Izzy doesn't know about welcome or moon directly, but I think implementing this as "whatever channel the silenced user spammed in, make it slow mode" should be fine. Let's say five minutes.

After all the debugging today, I have no reason to believe a silenced spammer could _break_ Izzy even if we never get around to this, so `level: minor`.

**Comment by Ixrec** [comment]
Izzy doing something on filter/spam violations for an already-silenced user came up in modchat again recently. This specific slowmode idea wasn't even mentioned, and in straw poll terms the old auto-ban idea essentially got 1 Weak Against and 1 Weak For which is hardly a consensus.

Thus I think we should formally shelve this issue until there's a clear demand.

**Comment by Ixrec** [comment]
Today timeouts got suggested as yet another thing Izzy could do in this scenario, and I like that option much better than auto-ban or auto-slowmode. Assuming we have the APIs to do an auto-timeout. EDIT: we do

**Comment by MercurialPony** [comment]
I'm actually not opposed to banning users either. In fact it's more fun if a regular gets themselves banned in which case we can award them the terminated badge (I'm assuming that's what it's for, right?). But either way works for me

**Comment by Ixrec** [comment]
I believe that updates the hypothetical straw poll on auto-banning to 2 Weak Fors and 2 Weak Against (now that we've noticed the timeout option I'm WA) 😅

If the mod team sentiment swings to a clear consensus on auto-banning it should be an easy change.
