### ISSUE TITLE
Automatic #⁠open-commissions removals and warnings

### ISSUE THREAD

**Issue by Ixrec** [Manechat/izzy-moonbot#529]
We have a rule about not soliciting commissions more than once a week. It'd be nice to detect this automatically.

This would probably involve a persistent cache in GeneralStorage similar to what `.roll` uses, but the entry point would have to be MessageReceived events instead of a command.

**Comment by MercurialPony** [comment]
Also it might be a good idea to implement a configurable "grace" period, say 5 or 10 minutes, that lets users make more posts after their initial one in case they need to add something.

Though there's a valid counterargument that they could just edit their post so I'm not sure
